export const elements = {
  productList: document.querySelector(".product__info__list"),
  productInfo: document.querySelectorAll(".product__sidebar__list--item"),
  categoryList: document.querySelector(".product__sidebar__list"),
  bannersList: document.querySelector(".prev"),
  homeCategoryList: document.querySelector(".category__items"),
  bannersDotsList: document.querySelector(".dot-container"),
  carouselItem: document.getElementsByClassName("carousel__item"),
  bannersDot: document.getElementsByClassName("dot"),
  productCategoryItem: "product__sidebar__list--item",
  productCategoryItemClass: ".product__sidebar__list--item",
  hightlightClass: "hightlight",
  getPassword: document.getElementById("password"),
  confirmPassword: "confirmPassword",
  currentURL: window.location.pathname,  
  cartList: document.getElementsByClassName("cart__product__list"),
  cartModal: document.getElementById("cart__modal"),  
  cart: document.getElementById("cart"),
  cartClose: "close",
  buyNow: "btn buy-now",
  cartPlus: "btn cart-plus",
  cartMinus: "btn cart-minus",
  cartItem: document.querySelector("#cart span")
};
